### ISSUE TITLE
FR: BaseSmartContractAccount `signMessageWith6492`

### ISSUE THREAD

**Issue by ForestP** [alchemyplatform/aa-sdk#107]
**Is your feature request related to a problem? Please describe.**

In `BaseSmartContractAccount` there is a method to sign a message using ERC-6492 `signMessageWith6492`.

This method currently throws `signMessageWith6492 not supported`.

Will this be supported in the future or should it be implemented by SDK Users?

If it should be implemented by SDK Users - is there a working example to reference?

**Comment by avasisht23** [comment]
Hey! Thanks for your question :)

`BaseSmartContractAccount` is an abstract class. So, for that method in particular, we expect classes that extend `BaseSmartContractAccount` to have their own implementation of that method.

Shortly, we'll be adding SCA implementations atop `BaseSmartContractAccount` that will implement `signMessageWith6492`. Stay tuned!

**Comment by moldy530** [comment]
@avasisht23 we can probably make this experience a little bit better by refactoring `BaseSmartContractAccount` to implement the `wrapWith6492` method and have `sign*With6492` methods call `this.isDeployed` and `this.sign*`.

That way devs only need to implement `sign*` in their implementations

**Comment by denniswon** [comment]
Resolved by https://github.com/OMGWINNING/aa-sdk-staging/pull/79

**Comment by avasisht23** [comment]
Dennis worked on this and we'll be adding this solution to the next version!
