### ISSUE TITLE
FR: Update the middleware util for `alchemyPaymasterAndDataMiddleware` to match `withAlchemy*` naming

### ISSUE THREAD

**Issue by moldy530** [alchemyplatform/aa-sdk#109]
**Describe the solution you'd like**
The `withAlchemyGasManager` middleware function helper is named differently from the `alchemyPaymasterAndDataMiddleware` function which creates a weird and confusing experience. We should have both match the `withAlchemy*` naming pattern and make sure both accurately reflect that one does gas estimation and one does not. One option is to merge them into `withAlchemyGasManager` and have a configuration parameter that handles the switching of when to use the with gas estimation logic or not

**Comment by avasisht23** [comment]
addressed! will include in next version
