### ISSUE TITLE
the client.ts file is causing build failures in React Native / Expo projects due to the line const isDev = window.location.hostname.includes("localhost");.

### ISSUE THREAD

**Issue by moldy530** [alchemyplatform/aa-sdk#1092]
@moldy530, the client.ts file is causing build failures in React Native / Expo projects due to the line const isDev = window.location.hostname.includes("localhost");.

I understand that Alchemy doesn't have a signer available for React Native yet, but [based on the documentation](https://accountkit.alchemy.com/resources/react-native), we can still use other aspects of Account Kit.

The issue arises because window and window.location are not available in React Native. I have tried adding polyfills as a workaround, but this hasn't resolved the problem. Just wanted to make you aware

_Originally posted by @CurtisStaples in https://github.com/alchemyplatform/aa-sdk/pull/1058#issuecomment-2421154394_

**Comment by moldy530** [comment]
@CurtisStaples thanks for reporting! I've created an issue but won't get to it until next week. I think the fix here is just to do some optional chaining on window, but we'll probs also not want to log from dev RN builds either. Is there a canonical way to check a dev build in RN?

**Comment by CurtisStaples** [comment]
Awesome, thanks for responding so quickly. There's a few ways you can likely check a dev build in RN:

1. Using the global `__DEV__` variable:
   This is a boolean that's true when running in development mode.

   ```javascript
   if (__DEV__) {
     console.log('Running in development mode');
   }
   ```

2. Checking `process.env.NODE_ENV`:
   ```javascript
   if (process.env.NODE_ENV === 'development') {
     console.log('Running in development mode');
   }
   ```

**Comment by moldy530** [comment]
Ok great! I imagine we'll refine this further down the line, but what we can do in the meantime is merge these checks with the location check into a isDev function and go from there. 

I'll tag you when I get something up and running.

**Comment by CurtisStaples** [comment]
great, thanks!

**Comment by CurtisStaples** [comment]
Tested, and it's working great. Thanks for fixing!
