### ISSUE TITLE
Provider and Account classes don't validate required params on creation

### ISSUE THREAD

**Issue by moldy530** [alchemyplatform/aa-sdk#143]
When creating an Account or Provider, the classes don't validate their required params. We should use something like Zod to get some runtime validation of constructor params so that people don't run into issues.

eg. If you set the `entryPointAddress` via `env`, you might assume it works because it works in dev and do `process.env.ENTRYPOINT_ADDRESS!` so typescript doesn't get mad at you, but at run time you'll get errors (sometimes these are not very intuitive errors either)

eg:
```
// request for provider.getAddress()
{"jsonrpc":"2.0","id":0,"method":"eth_call","params":[{"data":"0x9b249f6900000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000058000000893a26168158fbeadd9335be5bc96592e25fbfb9cf0000000000000000000000005acae01624d71f00907788c0deffd72754f63e4e00000000000000000000000000000000000000000000000000000000000000000000000000000000"},"latest"]}

// result
{
    "jsonrpc": "2.0",
    "id": 0,
    "error": {
        "code": -32000,
        "message": "stack underflow (0 <=> 13)"
    }
}
```

**Comment by calebcgates** [comment]
Hello @moldy530!

I'm interested in working on this feature. I have experience with Typescript, Unit Tests, SDKs, Alchemy, but I'm still figuring out some aspects Zod, recreating the exact errors, and understanding the format of your packages.

Thanks for considering my involvement, and I'm looking forward to contributing!

My approach is to:
- create the unit tests
- get those to run
- update the Zod checks 
- Determine where that code should live
- then confidently confirm it works once compiled through the unit tests and possible live testing

I've identified `export interface BaseSmartAccountParams` and `export abstract class BaseSmartContractAccount<` as the interface and class that expects `entryPointAddress?: Address;`.  My first goal will be to add Zod to this class.

**Comment by moldy530** [comment]
Hey @calebcgates thanks for , @avasisht23 is currently adding zod checks and run time validations for various classes. There's a series of open PRs currently that, when closed, will address this

**Comment by calebcgates** [comment]
Thanks @moldy530 if there's anything I can contribute in the mean time please point me in the right direction.  I'm looking to stay sharp and contribute to a meaningful project.
