### ISSUE TITLE
after 1.0 update new smart contracts were made 

### ISSUE THREAD

**Issue by softwarecurator** [alchemyplatform/aa-sdk#244]
Thanks for filling out this bug report. Please provide as much detail as possible.

If your issue is with Alchemy's RPC APIs and not the SDK please report your issue on (discord)[https://alchemy.com/discord].

### [REQUIRED] Environment

- Browser version:
- AA SDK version:
- Package:

### [REQUIRED] Describe the problem

was it on purpose new smart contracts were made per address? on optimism and optimism goerli

**Comment by moldy530** [comment]
Is this referring to `LightAccount`? Yea we had a breaking change introduced with 1.0 Light Accounts which changed the default factory address. Since the Light Account factory address has changed, the counterfactual addresses have also changed for light account
