### ISSUE TITLE
FR: Import library as simple es6 module in html

### ISSUE THREAD

**Issue by 0xqd** [alchemyplatform/aa-sdk#253]
**Is your feature request related to a problem? Please describe.**
Hi, first and foremost, thanks for creating such nice lib. I'm working on the application which doesn't use react as the framework, is there any example that import aa-sdk as simple es6 module.

**Describe the solution you'd like**
I would love to see an example as es module in pure html.

**Comment by moldy530** [comment]
> is there any example that import aa-sdk as simple es6 module
Oh yea that's a good call out. We don't currently have any examples of importing the library in pure HTML. Our getting started doc doesn't really use React ([link](https://accountkit.alchemy.com/overview/getting-started.html)). We do export our build as both `esm` and `cjs` distributions so your usecase should work. The only difference will be how you actually import that module in HTML directly. 

Lemme know if you get stuck with the getting started docs!
