### ISSUE TITLE
FR: Improve README

### ISSUE THREAD

**Issue by moldy530** [alchemyplatform/aa-sdk#29]
I'm creating this issue thread to track improvements to be made to the README.

If you've run into certain things that are unclear or wish were better documented, leave a comment here so I can incorporate it in to the next round of changes.

**Comment by moldy530** [comment]
Add documentation around the fact that we set the initCode for the account on UOs if the account is not deployed. What this means is that the account is always deployed on the first UO you submit for that account

**Comment by moldy530** [comment]
- [ ] update the README so that it leverages the new hd-account and private-key utils

**Comment by ebaizel** [comment]
update sample code to show how to use a gas manager and fetch gas estimations when using an ethersprovider

**Comment by moldy530** [comment]
- [ ] fix the README examples to match the new signatures for creating a smart account provider
- [ ] fix the README examples to use `rpcClient` instead of `provider` as the parameter in the `.connect()` lambda function
