### ISSUE TITLE
npm ERR404: npm i -s @alchemy/aa-signers

### ISSUE THREAD

**Issue by srihar5ha** [alchemyplatform/aa-sdk#296]
Can somebody point me in the right direction? 
@alchemy/aa-signers is not found. 
I'm working on this:  https://accountkit.alchemy.com/smart-accounts/signers/web3auth.html
I'm approaching here for a speedy resolution. I have a hackathon to compete. Thnx.

**Comment by therealharpaljadeja** [comment]
Seems like the package is not published on npm.

I think you can still clone this repo. Go to the package folder (packages/signers), and install it locally to use it.

You can use [npm link](https://docs.npmjs.com/cli/v10/commands/npm-link) for the same
