### ISSUE TITLE
Issues on using Optimism Sepolia with AA AlchemyProvider

### ISSUE THREAD

**Issue by cylim** [alchemyplatform/aa-sdk#343]
Thanks for filling out this bug report. Please provide as much detail as possible.

If your issue is with our RPC APIs and not the SDK please report your issue on (discord)[https://alchemy.com/discord].

### [REQUIRED] Environment

- Browser version: Brave
- AA SDK version: 1.2.3
- Package: "viem": "^1.21.0"

### [REQUIRED] Describe the problem
optimismSepolia in `viem/chains` doesn't have alchemy rpcUrls, I had created a PR to https://github.com/wevm/viem/pull/1623 with Alchemy RPC urls. There is a temporary workarounds stated in this issues.

#### Relevant code or sample repro:
```ts
import { optimismSepolia } from "viem/chains";

const provider = new AlchemyProvider({
      apiKey: ALCHEMY_API_KEY,
      chain: optimismSepolia,
    })
```

<img width="887" alt="Screenshot 2023-12-25 at 16 20 53" src="https://github.com/alchemyplatform/aa-sdk/assets/5622951/4b36a686-429c-470b-9d7f-ffea2089f19e">

#### Temporary Workarounds
```ts
import { optimismSepolia } from "viem/chains";

const opSepolia = {
  ...optimismSepolia, rpcUrls: {
    ...optimismSepolia.rpcUrls,
    alchemy: {
      http: ["https://opt-sepolia.g.alchemy.com/v2"],
      webSocket: ["wss://opt-sepolia.g.alchemy.com/v2"]
    }
  }
}

const provider = new AlchemyProvider({
      apiKey: ALCHEMY_API_KEY,
      chain: opSepolia,
    })
```

**Comment by therealharpaljadeja** [comment]
Why is this issue closed, the bug still persists not just for OP but for all chains, I am using Sepolia.

**Comment by cylim** [comment]
> Why is this issue closed, the bug still persists not just for OP but for all chains, I am using Sepolia.

If you check the viem repo, they accepted another PR which basically is just a copy of my PR. 
In case you faced the similar issues on other chains/rpc, you can use the workaround solution mentioned or create a PR to viem repo.

I will close this issues, since I am just providing an alternative workaround solutions, if anyone faced similar issues, they are able to find it from closed issues.
