### ISSUE TITLE
FR: Upgrade viem to 2.0

### ISSUE THREAD

**Issue by moldy530** [alchemyplatform/aa-sdk#352]
Viem has released version 2.0, so we should upgrade our library to 2.0 (https://viem.sh/docs/migration-guide.html#_2-0-x-breaking-changes)

TBD, will this be a breaking change for our library? I think yea since the assumption is users might be using viem as well, so they might experience breaking changes related to viem

**Comment by therealharpaljadeja** [comment]
[Yes](https://github.com/alchemyplatform/aa-sdk/issues/343)

**Comment by pepoospina** [comment]
Yes @moldy530 , there are breaking changes. 

The problem is that some tool's latest versions are already prepared for Viem 2 (Web3 Modal and wallet connect, for example), so they would break if I downgrade to Viem 1 just for Alchemy.
