### ISSUE TITLE
FR: Allow the creation of sub-accounts in LightAccount

### ISSUE THREAD

**Issue by afmeirelles** [alchemyplatform/aa-sdk#360]
**Is your feature request related to a problem? Please describe.**
A few months ago the ability to create multiple accounts for the same owner was discontinued [check here](https://github.com/alchemyplatform/aa-sdk/blame/main/packages/accounts/src/light-account/account.ts#L111). 
This means we can only have one smart account per EOA, so for devs building apps we'd still need to manage one EAO per user.

**Describe the solution you'd like**
It would be super useful if apps could create any number of smart accounts from a single EOA. If there are no security implications on the blockchain side, that'd be as simple as allowing the index param to be used again.

**Comment by moldy530** [comment]
This has been fixed with the latest version of LightAccount
