### ISSUE TITLE
Update the abitype to stable v1

### ISSUE THREAD

**Issue by AmanRaj1608** [alchemyplatform/aa-sdk#390]
The aa-core is using package `abitype/zod`. `abitype/zod` has been upgraded normally but the one in aa-core is using an outdated version. I can’t effect it or patch it cause it’s node modules and it’s in package.json

Error `Unable to resolve "abitype/zod" from "node_modules/@alchemy/aa-core/dist/cjs/account/schema.js"`

### [REQUIRED] Environment

- AA SDK version: 2.0.0
- Package: aa-core

Have tried using this [accountkit-react-native-boilerplate](https://github.com/alchemyplatform/accountkit-react-native-boilerplate). But seems a bit outdated.

Suggest to update it to [v1.0.0](https://github.com/wevm/abitype/releases) as it doesn't break anything.

**Comment by moldy530** [comment]
ah this should be fixed in aa-sdk v3 since we leverage the latest version of viem which brings v1.0.0 of abitype/zod with it
