### ISSUE TITLE
Make `eth_estimateUserOperationGas` result conform to bundler spec

### ISSUE THREAD

**Issue by kaiix** [alchemyplatform/aa-sdk#44]
According to the definition of [bundler-spec](https://github.com/eth-infinitism/bundler-spec/blob/9cafd4be1d9b21221a57bc06c219a73cbd6cdebd/src/schemas/transaction.yaml#L365), the validation gas result of the `eth_estimateUserOperationGas` should be called `verificationGas`, not `verificationGasLimit`.

I found Alchemy forked the spec and changes the [response content](https://github.com/alchemyplatform/bundler-spec/blob/21d8ec66c5bbdfc7856939d20ddcb30cd3473928/src/schemas/transaction.yaml#L371) (BTW: the dev forgot to change [a part of it](https://github.com/alchemyplatform/bundler-spec/blob/21d8ec66c5bbdfc7856939d20ddcb30cd3473928/src/schemas/transaction.yaml#L379)), but this change may prevent the wallet client from switching to use Alchemy bundler, since the other bundler implementations (e.g. [stackup](https://github.com/stackup-wallet/stackup-bundler)) conform to the spec.

(I know this maybe not the best place to address the issue, but there's no other repo suit for this, sorry for that)

**Comment by dancoombs** [comment]
Hi @kaiix, we’ve decided for now to stay consistent with the naming in ERC-4337 https://eips.ethereum.org/EIPS/eip-4337#-eth_estimateuseroperationgas, as we believe the naming in the bundler spec repo is a mistake and should be fixed. There is an open PR to do that https://github.com/eth-infinitism/bundler-spec/pull/4

**Comment by kaiix** [comment]
got, but I found almost other implementations are using `verificationGas`, so maybe Alchemy API can return both `verificationGas` & `verificationGasLimit` for compatibility.

**Comment by dancoombs** [comment]
That might make sense, although I'd prefer if we just update the spec to be consistent with the ERC. I'm going to push for that and if it seems like it will take a while we may consider updating for compatibility.

Any other issues regarding Alchemy's APIs directly and not the SDK can be directed to our [discord](https://alchemy.com/discord).
