### ISSUE TITLE
ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by indiejoseph** [alchemyplatform/aa-sdk#47]
### [REQUIRED] Environment

- Browser version: NodeJS 
- AA SDK version: 0.1.0-alpha.15
- Package: @alchemy/aa-core

### [REQUIRED] Describe the problem
Got error "Cannot find module `/Users/josephcheng/Projects/wear.pass/node_modules/@alchemy/aa-core/dist/esm/signer/local-account' imported from /Users/josephcheng/Projects/wear.pass/node_modules/@alchemy/aa-core/dist/esm/signer/hd-account.js`
I think this release doesn't include local-account.js file, only found local-account.d.ts

#### How to reproduce:
Install [0.1.0-alpha.15](https://www.npmjs.com/package/@alchemy/aa-core/v/0.1.0-alpha.15)
!npm install @alchemy/aa-core

#### Relevant code or sample repro:
!import("@alchemy/aa-core")

**Comment by moldy530** [comment]
this should be fixed in the latest release
