### ISSUE TITLE
createLightAccountAlchemyClient Has no parameter 'account'

### ISSUE THREAD

**Issue by gizm0duck** [alchemyplatform/aa-sdk#624]
The documentation for privy integration describes the following code 

`export const smartAccountClient = await createLightAccountAlchemyClient({
  account: {
    signer: privySigner,
  },
  chain: sepolia,
  apiKey: "YOUR_API_KEY",
});`

This generates a typescript error saying that account is not a valid parameter. How can we configure a smart account to use the privy signer in the latest version of alchemy aa?

**Comment by gizm0duck** [comment]
It seems like the `AlchemySmartAccountClientConfig` type is where the `account` param is defined and the `AlchemyLightAccountClientConfig` type which defines the parameters for createLightAccountAlchemyClient specifically omit's the account param. Is this intended?

**Comment by ashishkabuni** [comment]
Any update on this?

**Comment by moldy530** [comment]
hey sorry looking now

**Comment by moldy530** [comment]
that's correct that it doesn't. you should pass the `signer` directly to that method as:

```
createLightAccountAlchemyClient({
  signer: ...
})
```

https://accountkit.alchemy.com/packages/aa-alchemy/light-account-client/#createlightaccountalchemyclient
