### ISSUE TITLE
unhandledRejection: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by ashishkabuni** [alchemyplatform/aa-sdk#646]
Thanks for filling out this bug report. Please provide as much detail as possible.

If your issue is with our RPC APIs and not the SDK please report your issue on (discord)[https://alchemy.com/discord].

### [REQUIRED] Environment

- Browser version:
- AA SDK version: 3.11.1
- Package:  alchemy/aa-alchemy

### [REQUIRED] Describe the problem

Getting error when doing build for my nextjs project.

⨯ unhandledRejection: ReferenceError: document is not defined
    at createSigner (webpack-internal:///(ssr)/./node_modules/@alchemy/aa-alchemy/dist/esm/config/store/client.js:43:27)

**Comment by ashishkabuni** [comment]
Also getting this error:

 ⨯ node_modules/@alchemy/aa-alchemy/dist/esm/config/actions/getAccount.js (6:14) @ getAccount
 ⨯ ClientOnlyPropertyError: account is only available on the client

**Comment by moldy530** [comment]
this looks related to https://github.com/alchemyplatform/aa-sdk/issues/648, it should be fixed now
