### ISSUE TITLE
getCounterFactualAddress failed on react native

### ISSUE THREAD

**Issue by guilherme-correa-s** [alchemyplatform/aa-sdk#69]
### Environment

- Browser version: **react-native** 0.72.3
- AA SDK version: **@alchemy/aa-core** 0.1.0-alpha.19
- Package: **viem** 1.5.3

### Describe the problem
When we try to aa sdk in an android app with react native on expo the app crashes when calling a provider method, even when just calling getAddress().

The same code works on the browser with react/next. 

#### Relevant code or sample repro:
```js
import { LocalAccountSigner, SimpleSmartContractAccount, SmartAccountProvider } from '@alchemy/aa-core'
import { polygonMumbai } from 'viem/chains'

const owner = LocalAccountSigner.privateKeyToAccountSigner(
    'any_private_key'
)
const provider = new SmartAccountProvider(
    'https://polygon-mumbai.g.alchemy.com/v2',
    '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789',
    polygonMumbai // chain
).connect(
    rpcClient =>
    new SimpleSmartContractAccount({
        entryPointAddress: '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789',
        chain: polygonMumbai,
        factoryAddress: SIMPLE_ACCOUNT_FACTORY_ADDRESS,
        rpcClient,
        owner
    })
)
console.log('get address')
console.log(await provider.getAddress())
```
[issue.txt](https://github.com/alchemyplatform/aa-sdk/files/12281278/issue.txt)

**Comment by BrunoLeaoT** [comment]
I'm having the same problem when trying to use in a simple Node.Js + express

`const SIMPLE_ACCOUNT_FACTORY_ADDRESS =
  "0x9406Cc6185a346906296840746125a0E44976454";

const ENTRYPOINT_ADDRESS = "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"

async function test() {
  // 1. connect to an RPC Provider and a Wallet
  const alchemy = new Alchemy({
    apiKey: "key,
    network: Network.MATIC_MUMBAI,
  });
  const alchemyProvider = await alchemy.config.getProvider(); 

  let mnemonic = 'swim sample toss midnight wealth trend monster similar exile fresh divorce decrease'
  const owner = Wallet.fromMnemonic(mnemonic);

  // 2. Create the SimpleAccount signer
  // signer is an ethers.js Signer
  const signer = EthersProviderAdapter.fromEthersProvider(
    alchemyProvider,
    ENTRYPOINT_ADDRESS
  ).connectToAccount(
    (rpcClient) =>{
      const account = new SimpleSmartContractAccount({
        entryPointAddress: ENTRYPOINT_ADDRESS,
        chain: getChain(alchemyProvider.network.chainId),
        owner: convertWalletToAccountSigner(owner),
        factoryAddress: SIMPLE_ACCOUNT_FACTORY_ADDRESS,
        rpcClient,
      })
      return account
    }

  );

  console.log(signer)
  // 3. send a user op
  // const { hash } = await signer.sendUserOperation({
  //   target: "0xTargetAddress",
  //   data: "0xcallData",
  //   value: BigInt(2), // value: bigint or undefined
  // });
}

test()`

**Comment by moldy530** [comment]
@guilherme-correa-s  I wonder if this has to do with viem using `fetch` under the hood? is `fetch` available globally in react-native contexts?

@BrunoLeaoT can you share a stack trace?

**Comment by BrunoLeaoT** [comment]
Not sure how to explain this, but I was going to run this morning to get the stack trace and it didn't throwed any error this time. The only thing I've changed in the meantime was the node version. I was using 16 and now 18

**Comment by moldy530** [comment]
ah that probably did it! node 16 doesn't have fetch enabled by default, whereas node 18 has experimental fetch global api enabled by default

**Comment by An-dz** [comment]
@moldy530 Fetch is available but we've researched further and made some tests. Expo Go can't use native libraries so it's probably some native dependency. Anyway, the solution was to use a development build instead.

**Comment by denniswon** [comment]
https://github.com/alchemyplatform/aa-sdk/issues/154
