### ISSUE TITLE
docs: Update AlchemySigner docs

### ISSUE THREAD

**Issue by kevinweaver** [alchemyplatform/aa-sdk#701]
**Is this a request for new documentation or updates to existing documentation**
Existing Documentation

**If existing documentation, a clear summary of what needs to be changed**
The [AlchemySigner docs](https://accountkit.alchemy.com/signers/alchemy-signer/introduction.html) suggest using the `AlchemySigner` type, which is [deprecated](https://github.com/alchemyplatform/aa-sdk/blob/f07adbc92eb1c1f6a6d0f4f22ea483f1b978a326/packages/alchemy/src/signer/index.ts#L3) with a comment suggesting the use of `AlchemyWebSigner`. This type is entirely absent from docs, so it's possible this comment is a typo as well, perhaps `AlchemySmartSigner` or `SmartAccountSigner` are intended?

**If new documentation, a clear summary of what needs to be added**
Please update the docs if `AlchemySigner` is truly deprecated and differentiate between:
- `AlchemySigner`
- `AlchemyWebSigner`
- `AlchemySmartSigner`
- `SmartAccountSigner`
- `LocalAccountSigner` 
as different docs point to each of these.

**Additional context**
Additional documentation issue [here](https://github.com/alchemyplatform/aa-sdk/issues/688).

**Comment by moldy530** [comment]
this should all be up to date in the v4 docs now
