### ISSUE TITLE
FR: support `dropAndReplace` flow for UserOperations

### ISSUE THREAD

**Issue by noam-alchemy** [alchemyplatform/aa-sdk#82]
**Is your feature request related to a problem? Please describe.**
On occasion fee markets move and UOs get stuck as pending in the mempool. In those instances, it's often desirable to resubmit the UO so that it clears faster. To do so, it needs to be the higher of (1.1x the last price OR the new fee market price). 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by therealharpaljadeja** [comment]
I am assuming there is no RPC method for this...

So, I have to add the `dropAndReplaceUserOperation` function [here](https://github.com/alchemyplatform/aa-sdk/blob/main/packages/core/src/provider/base.ts) right?

The function will take in the type `UserOperationRequest`

https://github.com/alchemyplatform/aa-sdk/blob/e1caaeb6a31a4e022254787e1765722e30b4e4e0/packages/core/src/types.ts#L30-L53

Call `gasEstimator`, bump return values by 10%, and then call `sendUserOperation`

https://github.com/alchemyplatform/aa-sdk/blob/e1caaeb6a31a4e022254787e1765722e30b4e4e0/packages/core/src/provider/base.ts#L418-L430

Do the above steps seem fine? @noam-alchemy

**Comment by noam-alchemy** [comment]
Generally yes! One small correction is that it's actually the greater of 

`{Call gasEstimator AND lastUOFee * 1.1}`

So there's some element of either getting the status of the last UO (which is a feature coming soon on Rundler) or being able to track that in memory before defaulting to the latest gasEstimator value.

**Comment by therealharpaljadeja** [comment]
I have a small confusion...

Do I need to call `gasEstimator` or `feeDataGetter`?

`gasEstimator` returns the various gas limits whereas `feeDataGetter` returns the "fee per gas".

I am assuming that the limits don't change frequently but "fee per gas" do.

**Comment by moldy530** [comment]
I think you need to call both `gasEstimator` and `feeDataGetter` because the gas could have changed

using `UserOperationRequest` will not work with the middleware because the middleware expects the `UserOperationStruct` instead. I think it makes sense for the `dropAndReplace` method to take the `Request` as an input, but you'll need to add a conversion function to go from `UserOperationRequest -> UserOperationStruct` within the Provider (probs fine to keep that util private)

**Comment by moldy530** [comment]
I think you probably want the whole middleware stack to run on the struct not just gas and fee, so you should pull out the middleware execution function into a private method as well to use

**Comment by therealharpaljadeja** [comment]
What if I just call `buildUserOperation`? It goes through the entire process with all middlewares.

1. Convert `UserOperationRequest` to `UserOperationCallData`
2. Call `buildUserOperation`
3. Compare values for 10% change
4. If gasLimits change then `sendUserOperation`
5. If gasPrice change more than 10% then `sendUserOperation`
6. If not 5 and 6 then do nothing.

is this correct?

**Comment by moldy530** [comment]
I thought about that at first too, but the downside to using `buildUserOperation` is that you can only pass it `target, data, value`, but the useroperation could have been a batch execute or non-batch. 

Probs best to pull out the call to the middleware stack into a private method `_runMiddlewareStack` and use that in your method.

**Comment by therealharpaljadeja** [comment]
Is this how I am supposed to do comparisions?

`BigNumberish` is not part of viem and hence giving a lot of issues when comparing.

```js
if (newUO.callGasLimit && (fromHex(oldUO.callGasLimit, 'bigint') * 110n) / 100n < fromHex(toHex(newUO.callGasLimit.toString()), 'bigint')) {
            return this._sendUserOperation(newUO);
}
```

Please advise.

**Comment by moldy530** [comment]
you can go from `BigNumberish` to `BigInt` by just doing `BigInt(myBigNumberish)`

The logic for replace should:
1. run all middleware
2. set `max_priority_fee_per_gas` and `max_fee_per_gas` to:
```
newUo.max_priority_fee_per_gas = bigIntMax(newUo.max_priority_fee_per_gas, (oldUo.max_priority_fee_per_gas * 110n ) / 100n)
newUo.max_fee_per_gas = bigIntMax(newUo.max_fee_per_gas, (oldUo.max_fee_per_gas * 110n ) / 100n)
```
3. submit the newUO via `this._sendUserOperation`

see https://github.com/alchemyplatform/aa-sdk/blob/main/packages/core/src/provider/base.ts#L256 for `bigIntMax`

**Comment by moldy530** [comment]
This is addressed in https://github.com/OMGWINNING/aa-sdk-staging/pull/85
