### ISSUE TITLE
SetChain in multi chain doesn't work

### ISSUE THREAD

**Issue by InfiniteAengus** [alchemyplatform/aa-sdk#837]
Thanks for filling out this bug report. Please provide as much detail as possible.

If your issue is with our RPC APIs and not the SDK please report your issue on (discord)[https://alchemy.com/discord].

### [REQUIRED] Environment

- Browser version:
- AA SDK version: 3.18.2
- Package: 

### [REQUIRED] Describe the problem
I created a config to have multi chain by setting connections in config, but setChain from useChain hook doesn't work.

**Comment by LeifuChen** [comment]
@InfiniteAengus I encountered the same issue. The correct way to use the function is `setChain({ chain: xxx })`. The documentation needs to be updated.

**Comment by InfiniteAengus** [comment]
> @InfiniteAengus I encountered the same issue. The correct way to use the function is `setChain({ chain: xxx })`. The documentation needs to be updated.

Thank you. seems like it's working

**Comment by avarobinson** [comment]
@InfiniteAengus @LeifuChen Sorry about this! Glad you were able to debug and I've updated the doc. Thanks a lot for flagging 🙏
