### ISSUE TITLE
What is the reasoning behind having 2 types which are similar?

### ISSUE THREAD

**Issue by therealharpaljadeja** [alchemyplatform/aa-sdk#89]
https://github.com/alchemyplatform/aa-sdk/blob/38b2ebf6e1373c50a9cc1dbeea78f8f2ef3ee8d9/packages/core/src/signer/types.ts#L5-L9

https://github.com/alchemyplatform/aa-sdk/blob/38b2ebf6e1373c50a9cc1dbeea78f8f2ef3ee8d9/packages/core/src/account/simple.ts#L20-L24

Do the above types need refactoring to one?

**Comment by moldy530** [comment]
Good catch, I think we need to just kill the `SimpleSmartAccountOwner` and migrate everything to using `SmartAccountSigner`
