### ISSUE TITLE
FR: support modifying connection state of a provider instance without creating a new instance

### ISSUE THREAD

**Issue by moldy530** [alchemyplatform/aa-sdk#91]
**Is your feature request related to a problem? Please describe.**
When I change chains or connection params, I need to recreate the provider from scratch. This also means that if my provider was already connected, I need to reconnect it.

**Describe the solution you'd like**
I should be able to change the chain and connection params using methods on an existing provider instance. This should maintain the connected state and it should propagate these changes down through the connected account if it is connected already

**Comment by therealharpaljadeja** [comment]
Ah, I see you don't want to create the provider...

**Comment by moldy530** [comment]
yup exactly, ideally there's a method that's like `setChain` or `setConnection` that can change the chain and rpc config. This will likely need to be bubbled down to the connected account as well. It should then emit a `chainChanged` event

**Comment by therealharpaljadeja** [comment]
How would we go about this? @moldy530 there is no switch chain for Public client in viem...
