### ISSUE TITLE
Multi-chain does not work in 4.00-aplha.7

### ISSUE THREAD

**Issue by gabrielantonyxaviour** [alchemyplatform/aa-sdk#913]
The docs says it supports multi chain apps in the below link but when I try to implement the code, it says that the param chains does not exist.

https://aa-sdk-site-alpha.vercel.app/react/multi-chain-apps#update-your-config

I am using the version 4.0.0-alpha.7 for @account/core, @account/infra, @account/react

I am following the starter kit given in the docs
https://aa-sdk-site-alpha.vercel.app/react/quickstart#new-nextjs-project

Here is my repo for reference
https://github.com/thedanielmark/dropify/tree/gabriel-app/alchemy-app

**Comment by avarobinson** [comment]
Hey @gabrielantonyxaviour - confirmed that this is working in 4.0.0-alpha.10. The params passed to chains should be a list of chain objects not just the chain:
```
    chains: [
      {
        chain: baseSepolia, // optional: you can specify a policy ID for this chain, if you want to sponsor gas
        // policyId: "BASE_GAS_MANAGER_POLICY_ID",
      },
      {
        chain: arbitrumSepolia,
        // optional: you can specify a policy ID for this chain, if you want to sponsor gas
        // policyId: "SEPOLIA_GAS_MANAGER_POLICY_ID",
      },
    ],

```

Let me know if that resolves the issue.
